language: haxe

os:
  - linux

haxe:
  - "3.2.1"
  - "3.4.0-rc.1"
  - development

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib install hxcpp
  - haxelib dev inotify .

script:
  - haxe haxedoc.hxml
  - make ndll
  - haxe --cwd example/ build.hxml
